CREATE TABLE IF NOT EXISTS USERS (
  id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
  email clob CHECK(email like '%@%') NOT NULL UNIQUE,
  username clob NOT NULL,
  hash clob NOT NULL,
  profileid INTEGER NOT NULL,
  FOREIGN KEY (profileid) REFERENCES PROFILES(id)
);

CREATE TABLE IF NOT EXISTS PROFILES (
  id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
  userRole clob NOT NULL CHECK(  userRole in ('ROLE_ADMIN', 'ROLE_SUSER', 'ROLE_USER') ) default 'ROLE_USER'
);

CREATE  INDEX IF NOT EXISTS USER_INDEX 
ON USERS (email); 
